### PR TITLE
Add shortcut to trigger webrtc

### PR DESCRIPTION
**Pull request by cljoly**
I find having a shortcut really handy.

### CODE REVIEW

**Review by ChrisAntaki — APPROVED** [review]

**Comment by ChrisAntaki** [comment]
Thanks!

**Comment by ChrisAntaki** [comment]
Hopefully this will go live in the coming days

**Comment by ChrisAntaki** [comment]
It's live already, that was a fast review
https://addons.mozilla.org/en-US/firefox/addon/happy-bonobo-disable-webrtc/

**Comment by cljoly** [comment]
Awesome!

**Pull request merged**
